part of 'model.dart';


ScheduleView _$ScheduleViewFromJson(Map<String, dynamic> json) {
  return ScheduleView(
      scheduleId: json['scheduleId'] as int,
      scheduleItemId: json['scheduleItemId'] as int,
      empId: json['empId'] as int,
      empName: json['empName'] as String,
      eventType: json['eventType'] as int,
      repeatType: json['repeatType'] as int,
      cycle: json['cycle'] as int,
      notifyTime: json['notifyTime']  == null ? null : const CustomDateTimeConverter().fromJson(json['notifyTime'] as String),
      remindTime: json['remindTime'] == null ? null : const CustomTimeConverter().fromJson(json['remindTime'] as String),
      remindTimeUnit: json['remindTimeUnit'] as int,
      remindTimeQty: json['remindTimeQty'] as int,
      monRepeat: json['monRepeat'] as int,
      tueRepeat: json['tueRepeat'] as int,
      wedRepeat: json['wedRepeat'] as int,
      thuRepeat: json['thuRepeat'] as int,
      friRepeat: json['friRepeat'] as int,
      satRepeat: json['satRepeat'] as int,
      sunRepeat: json['sunRepeat'] as int,
      showMeAs: json['showMeAs'] as int,
      title: json['title'] as String,
      location: json['location'] as String,
      description: json['description'] as String,
      startDate: json['startDate']  == null ? null : const CustomDateTimeConverter().fromJson(json['startDate'] as String),
      endDate: json['endDate']  == null ? null : const CustomDateTimeConverter().fromJson(json['endDate'] as String),
      startTime: json['startTime']  == null ? null : const CustomDateTimeConverter().fromJson(json['startTime'] as String),
      endTime: json['endTime']  == null ? null : const CustomDateTimeConverter().fromJson(json['endTime'] as String),
      allDay: json['allDay'] as int,
      numOfDay: json['numOfDay'] == null ? null : double.parse(json['numOfDay'].toString()),
      remindType: json['remindType'] as int);
}

Map<String, dynamic> _$ScheduleViewToJson(ScheduleView instance) =>
    <String, dynamic>{
      'scheduleId': instance.scheduleId,
      'scheduleItemId': instance.scheduleItemId,
      'empId': instance.empId,
      'empName': instance.empName,
      'repeatType': instance.repeatType,
      'eventType': instance.eventType,
      'cycle': instance.cycle,
      'notifyTime': instance.notifyTime  == null ? null : const CustomDateTimeConverter().toJson(instance.notifyTime),
      'remindTime': instance.remindTime  == null ? null : const CustomTimeConverter().toJson(instance.remindTime),
      'remindTimeUnit': instance.remindTimeUnit,
      'remindTimeQty': instance.remindTimeQty,
      'monRepeat': instance.monRepeat,
      'tueRepeat': instance.tueRepeat,
      'wedRepeat': instance.wedRepeat,
      'thuRepeat': instance.thuRepeat,
      'friRepeat': instance.friRepeat,
      'satRepeat': instance.satRepeat,
      'sunRepeat': instance.sunRepeat,
      'showMeAs': instance.showMeAs,
      'title': instance.title,
      'description': instance.description,
      'location': instance.location,
      'allDay': instance.allDay,
      'remindType': instance.remindType,
      'numOfDay': instance.numOfDay,
      'startDate' : instance.startDate == null ? null : const CustomDateTimeConverter().toJson(instance.startDate),
      'endDate' : instance.endDate == null ? null : const CustomDateTimeConverter().toJson(instance.endDate),
      'startTime' : instance.startTime == null ? null : const CustomDateTimeConverter().toJson(instance.startTime),
      'endTime' : instance.endTime == null ? null : const CustomDateTimeConverter().toJson(instance.endTime),
    };